Updated gofmt job formatting

diff --git a/.github/workflows/go_build.yaml b/.github/workflows/go_build.yaml
--- a/.github/workflows/go_build.yaml
+++ b/.github/workflows/go_build.yaml
@@ -41,7 +41,14 @@ jobs:
 
     - name: Run gofmt
       if: matrix.os == 'ubuntu-latest' # Ensures only ran once.
-      run: FMT_RESULTS="$(gofmt -l .)"; if [ "$(wc -l <<< "$FMT_RESULTS")" -gt 0 ]; then echo $FMT_RESULTS | xargs -n1; exit 1; fi
+      run: |
+        FMT_RESULTS="$(gofmt -l .)";
+        if [ "$(wc -l <<< "$FMT_RESULTS")" -gt 0 ];
+        then
+          echo "'gofmt -l .' failed for files:"
+          echo $FMT_RESULTS | xargs -n1;
+          exit 1;
+        fi
 
     - name: Run go vet
       if: matrix.os == 'ubuntu-latest' # Ensures only ran once.
